import { type CSSProperties, type PointerEvent, type ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router';
import { clone, defaultPlans, isDate, localDate, type Activity, type Plan, type Preferences } from './domain';
import { useDayShaperStore } from './store';
const fallbackImages: Record<string, string> = {
  music: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=500&q=80', sports: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=500&q=80', dance: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=500&q=80', learning: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=500&q=80', food_drink: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=500&q=80', games: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=500&q=80', arts_culture: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=500&q=80', wellness: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=500&q=80', default: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=500&q=80'
};
const dateLabel = (value: string, options: Intl.DateTimeFormatOptions = { day: '2-digit', month: '2-digit', year: 'numeric' }) => new Intl.DateTimeFormat(navigator.language || 'en-US', options).format(new Date(`${value}T12:00:00`));
const categoryImage = (activity: Activity) => fallbackImages[String(activity.category || '').toLowerCase().replace(/[^a-z0-9]+/g, '_')] || fallbackImages.default;
const planForDate = (plan: Plan, date: string): Plan => ({ ...clone(plan), events: plan.events.map((event) => ({ ...event, time: `${dateLabel(date)} · ${event.time || 'Time flexible'}` })) });

function App() {
  const navigate = useNavigate();
  const route = useLocation();
  const date = useDayShaperStore((state) => state.date);
  const location = useDayShaperStore((state) => state.location);
  const cities = useDayShaperStore((state) => state.cities);
  const apiReady = useDayShaperStore((state) => state.apiReady);
  const plans = useDayShaperStore((state) => state.plans);
  const selectedPlan = useDayShaperStore((state) => state.selectedPlan);
  const savedPlans = useDayShaperStore((state) => state.savedPlans);
  const preferences = useDayShaperStore((state) => state.preferences);
  const resultMode = useDayShaperStore((state) => state.resultMode);
  const setDate = useDayShaperStore((state) => state.setDate);
  const setLocation = useDayShaperStore((state) => state.setLocation);
  const setCities = useDayShaperStore((state) => state.setCities);
  const setApiReady = useDayShaperStore((state) => state.setApiReady);
  const setPlans = useDayShaperStore((state) => state.setPlans);
  const setSelectedPlan = useDayShaperStore((state) => state.setSelectedPlan);
  const setSavedPlans = useDayShaperStore((state) => state.setSavedPlans);
  const setPreferences = useDayShaperStore((state) => state.setPreferences);
  const setResultMode = useDayShaperStore((state) => state.setResultMode);
  const [toast, setToast] = useState('');
  const toastTimer = useRef<number | undefined>(undefined);
  const notify = useCallback((message: string) => { window.clearTimeout(toastTimer.current); setToast(message); toastTimer.current = window.setTimeout(() => setToast(''), 1700); }, []);
  const shiftDate = useCallback((amount: number) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + amount); setDate(localDate(next)); }, [date, setDate]);

  useEffect(() => { fetch('/api/status').then((res) => res.json()).then((status) => setApiReady(Boolean(status.configured))).catch(() => setApiReady(false)); }, []);
  useEffect(() => { fetch('/api/cities').then((res) => res.json()).then((data: { cities?: { display_name: string }[] }) => { const names = data.cities?.map((city) => city.display_name).filter(Boolean); if (names?.length) setCities(names); }).catch(() => undefined); }, []);
  useEffect(() => { document.querySelector('.stage')?.scrollTo({ top: 0 }); }, [route.pathname]);

  const fetchPlans = useCallback(async () => {
    const fallback = defaultPlans.map((plan) => planForDate(plan, date));
    try {
      const response = await fetch('/api/recommendations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ location, date, preferences }) });
      const data = await response.json() as { plans?: Plan[]; error?: string };
      if (!response.ok) throw new Error(data.error);
      setPlans(data.plans?.length ? data.plans : fallback);
    } catch {
      setPlans(fallback);
      notify('Using curated plans while live planning is unavailable.');
    }
  }, [date, location, notify, preferences]);

  const savePlan = (plan: Plan) => { const saved = { ...plan, savedId: plan.savedId || `saved-${Date.now()}`, date, location, savedAt: new Date().toISOString() }; setSelectedPlan(saved); setSavedPlans([saved, ...savedPlans.filter((item) => item.savedId !== saved.savedId)]); return saved; };
  const choosePlan = (plan: Plan) => { savePlan(clone(plan)); navigate('/agenda'); notify('Your plan is ready.'); };
  const customizePlan = (plan?: Plan) => { if (plan) setSelectedPlan(clone(plan)); else setSelectedPlan({ id: '', title: 'My own plan', theme: 'Personal', summary: 'A plan made entirely by you.', score: 100, events: [] }); setResultMode('customize'); navigate('/results'); };
  const openSavedPlan = (plan: Plan) => { if (isDate(plan.date || null)) setDate(plan.date!); if (plan.location) setLocation(plan.location); setSelectedPlan(clone(plan)); navigate('/agenda'); };
  const planContext = <div className="plan-context"><span>⌖ <b>{location}</b></span><span>▣ <b>{dateLabel(date)}</b></span></div>;

  return <div className="app">
    <Sidebar notify={notify} />
    <main className="stage">
      <Routes>
        <Route path="/" element={<Home location={location} cities={cities} apiReady={apiReady} setLocation={setLocation} />} />
        <Route path="/planner" element={<Planner preferences={preferences} setPreferences={setPreferences} context={planContext} />} />
        <Route path="/availability" element={<Availability date={date} shiftDate={shiftDate} setDate={setDate} notify={notify} context={planContext} startResults={() => { setResultMode('loading'); navigate('/results'); }} />} />
        <Route path="/matching" element={<Navigate to="/results" replace />} />
        <Route path="/results" element={<Results mode={resultMode} setMode={setResultMode} plans={plans} choosePlan={choosePlan} customizePlan={customizePlan} fetchPlans={fetchPlans} source={selectedPlan} discovered={plans.flatMap((plan) => plan.events)} onSave={(plan) => { setSelectedPlan(plan); setResultMode('options'); navigate('/agenda'); notify('Your plan is ready.'); }} context={planContext} />} />
        <Route path="/editor" element={<Navigate to="/results" replace />} />
        <Route path="/agenda" element={<Agenda plan={selectedPlan} setPlan={setSelectedPlan} save={() => { savePlan(selectedPlan); notify('Saved to your plans.'); }} customize={() => { setResultMode('customize'); navigate('/results'); }} notify={notify} context={planContext} />} />
        <Route path="/plans" element={<SavedPlans date={date} savedPlans={savedPlans} shiftDate={shiftDate} setDate={setDate} openPlan={openSavedPlan} context={planContext} />} />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </main>
    <div className={`toast ${toast ? 'show' : ''}`}>{toast}</div>
  </div>;
}

function Sidebar({ notify }: { notify: (message: string) => void }) {
  return <aside className="side"><svg className="logo" viewBox="0 0 48 56" aria-label="ElseWhen"><path d="M23.5 31C8 23 9 10 20 3c7 7 8 17 3.5 28Z" fill="#6859bd"/><path d="M25 31c15-7 16-20 7-27-8 7-10 17-7 27Z" fill="#7c6bce"/><path d="M24 54V27" stroke="#6859bd" strokeWidth="2"/><path d="M24 40c-10-1-16-6-18-13 10-1 16 5 18 13Z" fill="#a496df"/></svg><nav className="nav"><NavLink to="/" end className={({ isActive }) => isActive ? 'active' : ''}><span>⌂</span><span>Home</span></NavLink><NavLink to="/planner" className={({ isActive }) => isActive ? 'active' : ''}><span>▦</span><span>Plan</span></NavLink><NavLink to="/plans" className={({ isActive }) => isActive ? 'active' : ''}><span>◴</span><span>Plans</span></NavLink><button onClick={() => notify('Settings are ready for the next pass.')}><span>⚙</span><span>Settings</span></button></nav><div className="avatar">JS</div></aside>;
}

function Home({ location, cities, apiReady, setLocation }: { location: string; cities: string[]; apiReady: boolean; setLocation: (value: string) => void }) {
  const navigate = useNavigate();
  return <section className="screen home active"><div className="date">{dateLabel(localDate(), { weekday: 'short', month: 'short', day: 'numeric' })}</div><div className="inner"><div className="sun">◒</div><h1>Good evening, Jamie</h1><p className="sub">Let’s turn your free time into something meaningful.</p><div className="search-controls" aria-label="Search details"><label className="search-field">⌖ <span>Plan near</span><select value={location} onChange={(event) => setLocation(event.target.value)}>{cities.map((city) => <option key={city}>{city}</option>)}</select></label><span className={`api-state ${apiReady ? 'ready' : ''}`}><i className="api-dot"/><span>{apiReady ? 'Live plans ready' : 'Curated plans'}</span></span></div><p className="home-note">You’ll choose the day and your availability in the next step.</p><div className="previews"><div><span className="round">♙</span>Tell us what matters<br/>right now</div><div><span className="round">◷</span>Choose when you’re<br/>free</div><div><span className="round">♨</span>Get personalized<br/>suggestions</div></div><button className="primary" onClick={() => navigate('/planner')}>Start planning &nbsp;→</button></div><Landscape /></section>;
}

function FlowHeader({ step, back, onBack, context, action }: { step: 1 | 2 | 3; back: string; onBack?: () => void; context: ReactNode; action?: ReactNode }) { const navigate = useNavigate(); return <header className="flow-header"><button className="back" onClick={() => onBack ? onBack() : navigate(back)} aria-label="Go back">‹</button><div className="flow-header-main"><div className="flow-steps" aria-label={`Step ${step} of 3`}>{['Meaning', 'Availability', 'Your plan'].map((label, index) => <div className={`flow-step ${index + 1 === step ? 'current' : index + 1 < step ? 'complete' : ''}`} key={label}><i>{index + 1 < step ? '✓' : index + 1}</i><span>{label}</span></div>)}</div>{context}</div>{action}</header>; }

function Planner({ preferences, setPreferences, context }: { preferences: Preferences; setPreferences: (value: Preferences) => void; context: ReactNode }) {
  const navigate = useNavigate(); const [selected, setSelected] = useState<keyof Preferences>('movement'); const canvas = useRef<HTMLDivElement>(null);
  const labels: Record<keyof Preferences, string> = { focus: 'Focus', movement: 'Movement', novelty: 'Novelty', connection: 'Connection' }; const emojis: Record<keyof Preferences, string> = { focus: '😐', movement: '🙂', novelty: '😌', connection: '😍' };
  const phrase = (v: Preferences[keyof Preferences]) => v.want >= 60 && v.capacity >= 60 ? 'Excited and ready' : v.want >= 60 ? 'Wanting this, gently' : v.capacity >= 60 ? 'Available, but not seeking' : 'Not for today';
  const move = (key: keyof Preferences, event: PointerEvent<HTMLDivElement>) => { if (!canvas.current || !event.currentTarget.hasPointerCapture(event.pointerId)) return; const rect = canvas.current.getBoundingClientRect(); const want = Math.max(10, Math.min(90, (event.clientX - rect.left) / rect.width * 100)); const capacity = Math.max(10, Math.min(90, 100 - (event.clientY - rect.top) / rect.height * 100)); setPreferences({ ...preferences, [key]: { want, capacity } }); };
  return <section className="screen active"><div className="inner"><FlowHeader step={1} back="/" context={<><span className="flow-caption">Step 1 of 3 · What matters today</span>{context}</>} action={<button className="skip" onClick={() => navigate('/availability')}>Skip</button>}/><h2>What feels meaningful today?</h2><p className="sub">Arrange the little markers until the space feels like you. There’s no right answer.</p><div className="plan-layout"><div className="axes interest-canvas-wrap"><div className="canvas-caption"><strong>Arrange what matters today</strong><span>Drag an emoji to change how it feels</span></div><div className="grid interest-canvas" ref={canvas}><div className="canvas-label canvas-label-top">I have room for this</div><div className="canvas-label canvas-label-bottom">Keep it gentle</div><div className="canvas-label canvas-label-left">Not really looking for this</div><div className="canvas-label canvas-label-right">I really want this</div>{(Object.keys(preferences) as (keyof Preferences)[]).map((key) => { const value = preferences[key]; const custom = { left: `${value.want}%`, top: `${100 - value.capacity}%`, '--marker-size': `${Math.round(40 + value.want * .34)}px`, '--emoji-size': `${Math.round(22 + value.want * .3)}px`, '--marker-opacity': (0.78 + value.want * .0022).toFixed(2), '--halo-color': value.want >= 60 && value.capacity >= 60 ? '#c9eb9aa6' : '#e8e1ffb8', '--halo-spread': value.want >= 60 && value.capacity >= 60 ? '16px' : '11px', '--motion-duration': value.capacity < 18 ? '0s' : `${(8.8 - value.capacity * .06).toFixed(2)}s` } as CSSProperties; return <div key={key} className={`mood ${key} ${selected === key ? 'sel' : ''} ${value.capacity < 18 ? 'still' : ''}`} style={custom} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); setSelected(key); }} onPointerMove={(event) => move(key, event)} onPointerUp={(event) => event.currentTarget.releasePointerCapture(event.pointerId)}><div className="face">{emojis[key]}</div><b>{labels[key]}</b></div>; })}<div className="canvas-status" aria-live="polite"><span>{labels[selected]}</span><strong>{phrase(preferences[selected])}</strong></div></div></div></div><div className="next"><button className="primary" onClick={() => navigate('/availability')}>Continue &nbsp;→</button></div></div></section>;
}

function Availability({ date, shiftDate, setDate, notify, context, startResults }: { date: string; shiftDate: (amount: number) => void; setDate: (value: string) => void; notify: (message: string) => void; context: ReactNode; startResults: () => void }) {
  const navigate = useNavigate(); const [connected, setConnected] = useState(''); const [freeAnyway, setFreeAnyway] = useState(false);
  const connect = (name: string) => { setConnected(name); notify('Calendar connected for this prototype.'); };
  return <section className="screen active"><div className="inner"><FlowHeader step={2} back="/planner" context={<><span className="flow-caption">Step 2 of 3 · Your availability</span>{context}</>}/><h2>When are you free?</h2><p className="sub">Pick the day here, then we’ll look for activities that fit your open time.</p><div className="connects">{['🌈  Connect Google', '●  Connect Apple', '▣  Connect Outlook'].map((name) => <button key={name} className={`connect ${connected === name ? 'on' : ''}`} onClick={() => connect(name)}>{connected === name ? '✓  Connected' : name}</button>)}</div><div className="cal-layout"><div><div className="dayhead"><button className="back" onClick={() => shiftDate(-1)}>‹</button><strong>{dateLabel(date, { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' })}</strong><button className="back" onClick={() => shiftDate(1)}>›</button><button className="soft" onClick={() => setDate(localDate())}>Today</button></div><div className="timeline"><div className="times">{['8 AM', '10 AM', '12 PM', '2 PM', '4 PM', '6 PM', '8 PM', '10 PM'].map((time) => <span key={time}>{time}</span>)}</div><div className="calgrid"><div className="block busy" style={{ top: 13, height: 48 }}><b>Morning Meeting</b>9:00 – 10:00 AM</div><div className="block busy" style={{ top: 98, height: 48 }}><b>Lunch with Alex</b>12:00 – 1:00 PM</div><div className="block free" style={{ top: 176, height: 102 }}><b>Free</b>3:00 – 6:00 PM</div><div className="block free" style={{ top: 288, height: 102 }}><b>Free</b>7:00 – 10:00 PM</div></div></div></div><aside className="availcard"><h3>Adjust your availability</h3><p className="sub" style={{ fontSize: 11 }}>Click on a free slot to exclude it, or mark a busy event as “free anyway.”</p><div className="legend"><span><i className="sw" style={{ background: '#eeedf5' }}/>Busy (from calendar)</span><span><i className="sw" style={{ background: '#eff8e8' }}/>Free time</span><span><i className="sw" style={{ background: '#e7e5f2' }}/>Excluded</span></div><div className="override"><b>Lunch with Alex</b><br/>12:00 – 1:00 PM<br/><button onClick={() => setFreeAnyway(!freeAnyway)}>{freeAnyway ? 'Marked free ✓' : 'Free anyway'}</button></div></aside></div><div className="next"><button className="primary" onClick={startResults}>See my possibilities &nbsp;→</button></div></div></section>;
}

function Results({ mode, setMode, plans, choosePlan, customizePlan, fetchPlans, source, discovered, onSave, context }: { mode: 'loading' | 'options' | 'customize'; setMode: (mode: 'loading' | 'options' | 'customize') => void; plans: Plan[]; choosePlan: (plan: Plan) => void; customizePlan: (plan?: Plan) => void; fetchPlans: () => Promise<void>; source: Plan; discovered: Activity[]; onSave: (plan: Plan) => void; context: ReactNode }) {
  const navigate = useNavigate();
  useEffect(() => {
    if (mode !== 'loading') return;
    let active = true;
    const started = Date.now();
    void fetchPlans().finally(() => window.setTimeout(() => { if (active) setMode('options'); }, Math.max(0, 1400 - (Date.now() - started))));
    return () => { active = false; };
  }, [fetchPlans, mode, setMode]);
  const header = <FlowHeader step={3} back="/availability" onBack={mode === 'customize' ? () => setMode('options') : undefined} context={<><span className="flow-caption">Step 3 of 3 · Your possibilities</span>{context}</>} action={mode === 'options' ? <button className="edit" onClick={() => navigate('/planner')}>Edit preferences</button> : undefined}/>;
  if (mode === 'loading') return <section className="screen matching active"><div className="inner">{header}<div className="spark">✦</div><h2>Shaping a few possibilities</h2><p className="sub">Searching for real events, experiences, and activities<br/>that fit your time, location, and what matters to you...</p><div className="checks"><div className="check"><span className="tick">✓</span>Reading your preferences</div><div className="check"><span className="tick">✓</span>Checking your open time</div><div className="check"><span className="tick spin"/>Building distinct plan options</div></div><div className="moment"><span className="round" style={{ margin: 0 }}>♨</span><div><b>Good things take a moment</b><br/><span className="sub" style={{ fontSize: 12 }}>We’re putting together a few different ways your time could feel.</span></div></div></div></section>;
  if (mode === 'customize') return <section className="screen editor active"><div className="inner">{header}<Editor source={source} discovered={discovered} onSave={onSave} onCancel={() => setMode('options')}/></div></section>;
  return <section className="screen results active"><div className="inner">{header}<div className="title-row"><div><h2>Choose a plan that fits</h2><p className="sub">Three different ways to spend your time. Pick one as-is or make it yours.</p></div></div><div className="plan-options">{plans.map((plan, index) => <article className={`plan-card ${index === 0 ? 'best' : ''}`} key={plan.id}><div className="plan-card-head"><span className="plan-theme">{plan.theme}</span><span className="plan-score">{Math.max(1, Math.min(99, plan.score || 80))}% fit</span><h3>{plan.title}</h3><div className="plan-summary">{plan.summary}</div></div><div className="plan-events">{plan.events.map((event, eventIndex) => <div className="plan-event" key={`${event.title}-${eventIndex}`}><SafeImage activity={event}/><div><b>{event.title}</b><span>{event.time || 'Time flexible'}</span><br/>{event.sourceUrl?.startsWith('https://onhuddle.co/event/') && <a href={event.sourceUrl} target="_blank" rel="noreferrer">View event ↗</a>}</div></div>)}</div><div className="plan-actions"><button className="customize-plan" onClick={() => customizePlan(plan)}>Customize</button><button className="choose-plan" onClick={() => choosePlan(plan)}>Use this plan</button></div></article>)}</div><div className="blank-plan"><div><b>None of these feel right?</b>Build a completely new plan with your own activities and timing.</div><button className="soft" onClick={() => customizePlan()}>＋ &nbsp;Start from scratch</button></div></div></section>;
}

function SafeImage({ activity }: { activity: Activity }) { const [src, setSrc] = useState(activity.img || categoryImage(activity)); useEffect(() => setSrc(activity.img || categoryImage(activity)), [activity]); return <img src={src} onError={() => setSrc(categoryImage(activity))} alt=""/>; }

function Editor({ source, discovered, onSave, onCancel }: { source: Plan; discovered: Activity[]; onSave: (plan: Plan) => void; onCancel: () => void }) {
  const [name, setName] = useState(source.title || 'My own plan'); const [activities, setActivities] = useState<Activity[]>(source.events.length ? clone(source.events) : [{ title: '' }]); const [picker, setPicker] = useState(false);
  const update = (index: number, key: keyof Activity, value: string) => setActivities((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const save = () => { const events = activities.filter((item) => item.title.trim()).map((item) => ({ ...item, title: item.title.trim(), time: item.time?.trim() || 'Time flexible', place: item.place?.trim() || 'Place flexible' })); if (!events.length) return; onSave({ ...source, id: source.id || `custom-${Date.now()}`, title: name.trim() || 'My plan', theme: source.theme || 'Personal', summary: source.summary || 'A plan made entirely by you.', score: source.score || 100, events }); };
  return <><h2>{source.id ? 'Customize this plan' : 'Create a new plan'}</h2><p className="sub">Change any activity, time, or place—or add something completely your own.</p><div className="editor-form"><label className="field">Plan name<input maxLength={80} value={name} onChange={(event) => setName(event.target.value)} placeholder="My perfect afternoon"/></label><div className="editor-activities">{activities.map((activity, index) => <div className="editor-row" key={`${activity.title}-${index}`}><label className="field">Activity<input maxLength={120} value={activity.title} onChange={(event) => update(index, 'title', event.target.value)} placeholder="What would you like to do?"/></label><label className="field">Time<input maxLength={80} value={activity.time || ''} onChange={(event) => update(index, 'time', event.target.value)} placeholder="e.g. 7:00 – 8:30 PM"/></label><label className="field">Place<input maxLength={100} value={activity.place || ''} onChange={(event) => update(index, 'place', event.target.value)} placeholder="Where?"/></label><button className="remove-activity" onClick={() => setActivities((items) => items.length === 1 ? [{ title: '' }] : items.filter((_, itemIndex) => itemIndex !== index))} aria-label="Remove activity">×</button></div>)}</div>{picker && <div className="activity-picker"><div className="activity-picker-head"><div><h3>Choose a discovered event</h3><p>Pick from the events we found for this planning session.</p></div><button className="soft" onClick={() => setPicker(false)}>Close</button></div><div className="activity-picker-list">{discovered.length ? discovered.map((activity, index) => <button className="discovered-activity" key={`${activity.title}-${index}`} onClick={() => { setActivities((items) => [...items, clone(activity)]); setPicker(false); }}><span><b>{activity.title}</b><span>{activity.time || 'Time flexible'} · {activity.place || 'Place flexible'}</span></span><em>Add</em></button>) : <div className="picker-empty">No discovered events are available yet. Create a custom activity instead.</div>}</div></div>}<div className="editor-buttons"><div><button className="soft" onClick={() => setPicker(true)}>＋ Choose discovered event</button><button className="soft" onClick={() => setActivities((items) => [...items, { title: '' }])}>＋ Create custom</button></div><div><button className="soft" onClick={onCancel}>Cancel</button><button className="primary" onClick={save}>Use this plan &nbsp;→</button></div></div></div></>;
}

function Agenda({ plan, setPlan, save, customize, notify, context }: { plan: Plan; setPlan: (plan: Plan) => void; save: () => void; customize: () => void; notify: (message: string) => void; context: ReactNode }) {
  const navigate = useNavigate(); const remove = (index: number) => setPlan({ ...plan, events: plan.events.filter((_, eventIndex) => eventIndex !== index) });
  return <section className="screen agenda active"><div className="inner">{context}<div className="title-row"><div><div className="agenda-title-note"><h2>{plan.title || 'Your plan'}</h2><span className="plan-theme">{plan.theme || 'Personal'}</span></div><p className="sub">Your chosen plan is ready. You can still adjust it anytime.</p></div><div className="actions"><button className="soft" onClick={customize}>✎ &nbsp;Modify</button><button className="primary" onClick={save}>▣ &nbsp;Save</button><button className="soft" onClick={() => notify('Share link copied.')}>♧ &nbsp;Share</button></div></div><div className="planlist">{plan.events.length ? plan.events.map((event, index) => <article className="item" key={`${event.title}-${index}`}><div className="picon">{event.img ? <SafeImage activity={event}/> : '✦'}</div><div className="copy">{event.time || 'Time flexible'}<strong>{event.title}</strong><span className="sub" style={{ fontSize: 11 }}>{event.place || 'Place flexible'}</span></div><button className="remove-agenda" onClick={() => remove(index)} aria-label="Remove activity">×</button></article>) : <div className="empty-agenda">This plan is empty. <button className="soft" onClick={customize}>Add an activity</button></div>}</div><div className="mantra">“Time well spent feels different.”</div></div><Landscape short/></section>;
}

function SavedPlans({ date, savedPlans, shiftDate, setDate, openPlan, context }: { date: string; savedPlans: Plan[]; shiftDate: (amount: number) => void; setDate: (value: string) => void; openPlan: (plan: Plan) => void; context: ReactNode }) {
  const navigate = useNavigate(); const plans = useMemo(() => savedPlans.filter((plan) => plan.date === date), [date, savedPlans]);
  return <section className="screen plans active"><div className="inner">{context}<div className="title-row"><div><h2>Your plans</h2><p className="sub">Browse the plans you’ve saved for each day.</p></div><div className="plans-header-actions"><div className="date-picker date-picker-compact" aria-label="Browse plans by date"><button onClick={() => shiftDate(-1)} aria-label="Previous date">‹</button><label><span aria-hidden="true">▣</span><span>{dateLabel(date)}</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} aria-label="Browse plans by date"/></label><button onClick={() => shiftDate(1)} aria-label="Next date">›</button></div><button className="edit" onClick={() => navigate('/')}>＋ &nbsp;New plan</button></div></div><div className="plans-browser"><div className="saved-plans">{plans.length ? plans.map((plan) => <article className="saved-plan" key={plan.savedId || plan.id}><div><span className="plan-theme">{plan.theme || 'Personal'}</span><h3>{plan.title || 'Untitled plan'}</h3><p>{plan.location || 'Location flexible'} · {plan.events.length} {plan.events.length === 1 ? 'activity' : 'activities'}</p></div><button className="soft" onClick={() => openPlan(plan)}>Open</button></article>) : <div className="plans-empty"><h3>No saved plans for {dateLabel(date, { month: 'long', day: 'numeric' })}</h3><p>Choose a plan and save it here when you’re ready.</p><button className="soft" onClick={() => navigate('/')}>Plan this day</button></div>}</div></div></div></section>;
}

function Landscape({ short = false }: { short?: boolean }) { return <div className="land" style={short ? { height: 160, opacity: .45 } : undefined}><i className="hill h1"/><i className="hill h2"/><i className="hill h3"/>{!short && <><i className="lake"/><div className="note">A kinder way<br/>to plan your time</div></>}</div>; }

export default App;
